#!/bin/sh

HEADER="// Autogenerated by smufl_data.sh, do not manually modify."

{
    echo $HEADER
    jq '"\tk" + (keys_unsorted[] | ./"" | first |= ascii_upcase | add) + ","' -r < ./data/glyphnames.json
} > smufl/data/glyph_ids.h

{
    echo $HEADER
    jq '"\t\"" + (keys_unsorted[] | gsub("\""; "\\\"")) + "\","' -r < ./data/glyphnames.json
} > smufl/data/glyph_names.h

{
    echo $HEADER
    jq 'to_entries[] | ["\t\"", (.value.description | gsub("\""; "\\\"")), "\","] | join("")' -r < ./data/glyphnames.json
} > smufl/data/glyph_descriptions.h


{
    echo $HEADER
    jq '"\t" + (to_entries[] | (.value.codepoint | gsub("U\\+"; "0x"))) + ","' -r < ./data/glyphnames.json
} > smufl/data/glyph_codepoints.h
