#!/bin/sh
# Copyright (C) 2023 Marijn Kruisselbrink <mek@google.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 
HEADER="// Autogenerated by gen_smufl_data.sh, do not manually modify."

{
    echo $HEADER
    jq '"\tk" + (keys_unsorted[] | ./"" | first |= ascii_upcase | add) + ","' -r < ./smufl/glyphnames.json
} > engrave/smufl/glyph_ids.h

{
    echo $HEADER
    jq '"\t\"" + (keys_unsorted[] | gsub("\""; "\\\"")) + "\","' -r < ./smufl/glyphnames.json
} > engrave/smufl/glyph_names.h

{
    echo $HEADER
    jq 'to_entries[] | ["\t\"", (.value.description | gsub("\""; "\\\"")), "\","] | join("")' -r < ./smufl/glyphnames.json
} > engrave/smufl/glyph_descriptions.h


{
    echo $HEADER
    jq '"\t" + (to_entries[] | (.value.codepoint | gsub("U\\+"; "0x"))) + ","' -r < ./smufl/glyphnames.json
} > engrave/smufl/glyph_codepoints.h
