#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
from waflib import Options, Node
import os

# Mandatory variables
top = '.'
out = 'build'

# Version of this package (even if built as a child)
MAJOR = '0'
MINOR = '0'
MICRO = '0'
ENGRAVE_VERSION = "%s.%s.%s" % (MAJOR, MINOR, MICRO)

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
ENGRAVE_LIB_VERSION = '0.0.0'

# Variables for 'waf dist'
APPNAME = 'engrave'
VERSION = ENGRAVE_VERSION
I18N_PACKAGE = 'libengrave'

engrave_sources = [
    'clef.cc',
    'font_data.cc',
    'glyph.cc',
    'key_signature.cc',
    'render_context.cc',
]

engrave_use = [
    'libpbd',
]

engrave_uselibs = [
    'BOOST',
    'CAIROMM',
    'GLIBMM',
]

path_prefix = 'libs/engrave'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    opts = Options.options
    if opts.build_tests:
        autowaf.check_pkg(conf, 'gtest', uselib_store='GTEST', mandatory=True)
        autowaf.check_pkg(conf, 'gtest_main', uselib_store='GTEST_MAIN', mandatory=True)

def build(bld):
    # Library
    if bld.is_defined ('INTERNAL_SHARED_LIBS'):
        obj = bld.shlib(features = 'cxx cxxshlib', source=engrave_sources)
        obj.defines = [ 'LIBSMUFL_DLL_EXPORTS=1' ]
    else:
        obj = bld.stlib(features = 'cxx cxxstlib', source=engrave_sources)
        obj.cxxflags = [ bld.env['compiler_flags_dict']['pic'] ]
        obj.cflags   = [ bld.env['compiler_flags_dict']['pic'] ]
        obj.defines  = []
    
    obj.export_includes = ['.']
    obj.includes     = ['.']
    obj.name         = 'libengrave'
    obj.target       = 'engrave'
    obj.vnum         = ENGRAVE_LIB_VERSION
    obj.install_path = bld.env['LIBDIR']
    obj.defines     += [ 'PACKAGE="' + I18N_PACKAGE + '"' ]
    obj.uselib       = engrave_uselibs
    obj.use          = engrave_use

    bld.install_files(bld.env['DATADIR'], 'fonts/Leland/Leland.otf')
    bld.install_files(bld.env['DATADIR'], 'fonts/Leland/leland_metadata.json')

    if bld.env['BUILD_TESTS'] and bld.is_defined('HAVE_GTEST'):
        # Static library (for unit test code coverage)
        obj = bld(features = 'cxx cstlib')
        obj.source         = engrave_sources
        obj.export_includes = ['.']
        obj.includes       = ['.']
        obj.name           = 'libengrave_static'
        obj.target         = 'engrave_static'
        obj.uselib         = engrave_uselibs
        obj.use            = engrave_use
        obj.vnum           = ENGRAVE_LIB_VERSION
        obj.install_path   = ''
        if bld.env['TEST_COVERAGE']:
             obj.linkflags      = ['--coverage']
             obj.cflags         = ['--coverage']
             obj.cxxflags       = ['--coverage']
        obj.defines        = ['PACKAGE="libengrave"']

        # Unit tests
        obj              = bld(features = 'cxx cxxprogram')
        obj.source       = [
                'test/clef_test.cc',
                'test/key_signature_test.cc',
                ]
        obj.includes     = ['.']
        obj.use          = ['libengrave_static']
        obj.uselib       = ['GTEST_MAIN']
        obj.target       = 'run-tests'
        obj.name         = 'libengrave-tests'
        obj.install_path = ''
        obj.defines      = ['PACKAGE="libengravetest"']
        if bld.env['TEST_COVERAGE']:
            obj.linkflags      = ['--coverage']
            obj.cflags         = ['--coverage']
            obj.cxxflags       = ['--coverage']
        if bld.is_defined('NEED_INTL'):
            obj.linkflags = ' -lintl'

def test(ctx):
    pass

def shutdown():
    autowaf.shutdown()
